update oai examples to gpt-4o-mini
langchain-ai/langsmith-docs pull request #504
Opened 2024-11-04 19:36 UTC by baskaryan

2024-11-04 20:35 UTC, hinthornw approved these changes

2024-11-04 20:36 UTC, hinthornw requested changes
is there a 4o mini instruct model?

2024-11-04 20:40 UTC, baskaryan commented
> is there a 4o mini instruct model?

good catch, undoing

2024-11-06 18:29 UTC, hinthornw approved these changes

2024-11-06 18:31 UTC, merged